import {
  AGENT_SESSION_JSON_SCHEMA,
  CHAT_MESSAGE_JSON_SCHEMA,
  CHAT_RECORD_JSON_SCHEMA,
  EVENT_RECORD_JSON_SCHEMA,
  FLOW_RECORD_JSON_SCHEMA,
  FORM_RECORD_JSON_SCHEMA,
  GOAL_RECORD_JSON_SCHEMA,
  MCP_AGENT_SESSION_CREATE_INPUT,
  MCP_AGENT_SESSION_GET_INPUT,
  MCP_AGENT_SESSION_LIST_INPUT,
  MCP_AGENT_SESSION_LIST_OUTPUT,
  MCP_CHAT_GET_INPUT,
  MCP_CHAT_LIST_INPUT,
  MCP_CHAT_LIST_OUTPUT,
  MCP_CHAT_MESSAGES_LIST_INPUT,
  MCP_CHAT_MESSAGES_LIST_OUTPUT,
  MCP_CHAT_SEND_INPUT,
  MCP_EVENT_CREATE_INPUT,
  MCP_EVENT_DELETE_INPUT,
  MCP_EVENT_GET_INPUT,
  MCP_EVENT_LIST_INPUT,
  MCP_EVENT_LIST_OUTPUT,
  MCP_EVENT_UPDATE_INPUT,
  MCP_FLOW_CREATE_INPUT,
  MCP_FLOW_DELETE_INPUT,
  MCP_FLOW_GET_INPUT,
  MCP_FLOW_LIST_INPUT,
  MCP_FLOW_LIST_OUTPUT,
  MCP_FORM_CREATE_INPUT,
  MCP_FORM_DELETE_INPUT,
  MCP_FORM_GET_INPUT,
  MCP_FORM_LIST_INPUT,
  MCP_FORM_LIST_OUTPUT,
  MCP_GOAL_CREATE_INPUT,
  MCP_GOAL_DELETE_INPUT,
  MCP_GOAL_GET_INPUT,
  MCP_GOAL_LIST_INPUT,
  MCP_GOAL_LIST_OUTPUT,
  MCP_GOAL_UPDATE_INPUT,
  MCP_MOMENT_COMMENT_CREATE_INPUT,
  MCP_MOMENT_COMMENTS_LIST_INPUT,
  MCP_MOMENT_COMMENTS_LIST_OUTPUT,
  MCP_MOMENT_CREATE_INPUT,
  MCP_MOMENT_GET_INPUT,
  MCP_MOMENT_LIST_INPUT,
  MCP_MOMENT_LIST_OUTPUT,
  MCP_NOTE_CREATE_INPUT,
  MCP_NOTE_DELETE_INPUT,
  MCP_NOTE_GET_INPUT,
  MCP_NOTE_LIST_INPUT,
  MCP_NOTE_LIST_OUTPUT,
  MCP_NOTE_UPDATE_INPUT,
  MCP_PROFILE_GET_INPUT,
  MCP_SCOPE_CATALOG_INPUT,
  MCP_SUCCESS_OUTPUT,
  MCP_TAG_CREATE_INPUT,
  MCP_TAG_DELETE_INPUT,
  MCP_TAG_LIST_INPUT,
  MCP_TAG_LIST_OUTPUT,
  MCP_THREAD_MESSAGE_CREATE_INPUT,
  MCP_THREAD_MESSAGES_LIST_INPUT,
  MCP_THREAD_MESSAGES_LIST_OUTPUT,
  MCP_TOKEN_INFO_INPUT,
  MCP_TOKEN_REFRESH_INPUT,
  MCP_TRASH_LIST_INPUT,
  MCP_TRASH_LIST_OUTPUT,
  MCP_TRASH_PURGE_INPUT,
  MCP_TRASH_RESTORE_INPUT,
  MCP_WORKSPACE_COLLABORATOR_ADD_INPUT,
  MCP_WORKSPACE_COLLABORATORS_LIST_INPUT,
  MCP_WORKSPACE_COLLABORATORS_LIST_OUTPUT,
  MCP_WORKSPACE_CREATE_INPUT,
  MCP_WORKSPACE_DELETE_INPUT,
  MCP_WORKSPACE_GET_INPUT,
  MCP_WORKSPACE_LIST_INPUT,
  MCP_WORKSPACE_LIST_OUTPUT,
  MCP_WORKSPACE_UPDATE_INPUT,
  MOMENT_COMMENT_JSON_SCHEMA,
  MOMENT_RECORD_JSON_SCHEMA,
  NOTE_RECORD_JSON_SCHEMA,
  PROFILE_RECORD_JSON_SCHEMA,
  SCOPE_CATALOG_JSON_SCHEMA,
  TAG_RECORD_JSON_SCHEMA,
  THREAD_MESSAGE_JSON_SCHEMA,
  TOKEN_INFO_JSON_SCHEMA,
  TOKEN_REFRESH_JSON_SCHEMA,
  WORKSPACE_RECORD_JSON_SCHEMA,
} from '@/sdk/contracts';
import type { McpTool } from '@/lib/mcp/types';

export type { McpTool, McpToolAnnotation } from '@/lib/mcp/types';

export const MCP_TOOLS: McpTool[] = [
  // ── 1. Profile / Authentication ──
  {
    name: 'get_my_profile',
    description: 'Retrieve identity details, active permissions, and scopes for the currently authenticated actor (user or agent).',
    inputSchema: MCP_PROFILE_GET_INPUT,
    outputSchema: PROFILE_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 1.0 },
  },
  {
    name: 'get_token_info',
    description: 'Inspect active personal access token metadata, authorized permission scopes, expiration, and rate limits.',
    inputSchema: MCP_TOKEN_INFO_INPUT,
    outputSchema: TOKEN_INFO_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.9 },
  },
  {
    name: 'list_available_scopes',
    description: 'List all permission scopes available in the Kylrix ecosystem catalog.',
    inputSchema: MCP_SCOPE_CATALOG_INPUT,
    outputSchema: SCOPE_CATALOG_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.8 },
  },
  {
    name: 'refresh_token_scopes',
    description: 'Refresh or adjust permission scopes on the current active Bearer PAT token on the fly. Allows autonomous agents to dynamically grant themselves needed workspace and agentic scopes.',
    inputSchema: MCP_TOKEN_REFRESH_INPUT,
    outputSchema: TOKEN_REFRESH_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, idempotent: true, priority: 0.9 },
  },

  // ── 2. Workspaces (schemas from sdk/contracts/workspaces.ts) ──
  {
    name: 'list_workspaces',
    description: 'List all active human and agent workspaces accessible to the authenticated actor.',
    inputSchema: MCP_WORKSPACE_LIST_INPUT,
    outputSchema: MCP_WORKSPACE_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.9 },
  },
  {
    name: 'get_workspace',
    description: 'Retrieve detailed metadata and linked status for a specific workspace.',
    inputSchema: MCP_WORKSPACE_GET_INPUT,
    outputSchema: WORKSPACE_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.8 },
  },
  {
    name: 'create_workspace',
    description: 'Create a new project or agent workspace.',
    inputSchema: MCP_WORKSPACE_CREATE_INPUT,
    outputSchema: WORKSPACE_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.8 },
  },
  {
    name: 'update_workspace',
    description: 'Update the title, summary, or visibility of an existing workspace.',
    inputSchema: MCP_WORKSPACE_UPDATE_INPUT,
    outputSchema: WORKSPACE_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.7 },
  },
  {
    name: 'delete_workspace',
    description: 'Delete a workspace and cascade its internal links.',
    inputSchema: MCP_WORKSPACE_DELETE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.5 },
  },
  {
    name: 'list_workspace_collaborators',
    description: 'List team members and collaborators attached to a workspace.',
    inputSchema: MCP_WORKSPACE_COLLABORATORS_LIST_INPUT,
    outputSchema: MCP_WORKSPACE_COLLABORATORS_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.6 },
  },
  {
    name: 'add_workspace_collaborator',
    description: 'Invite or add a user or agent as a collaborator on a workspace.',
    inputSchema: MCP_WORKSPACE_COLLABORATOR_ADD_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.6 },
  },

  // ── 3. Notes & Ideas (schemas from sdk/contracts/notes.ts) ──
  {
    name: 'list_notes',
    description: 'List notes and ideas, with optional workspace filtering.',
    inputSchema: MCP_NOTE_LIST_INPUT,
    outputSchema: MCP_NOTE_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.95 },
  },
  {
    name: 'get_note',
    description: 'Retrieve full markdown content, title, tags, and metadata for a specific note.',
    inputSchema: MCP_NOTE_GET_INPUT,
    outputSchema: NOTE_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.9 },
  },
  {
    name: 'create_note',
    description: 'Create a new markdown note or idea, optionally linking it to a workspace.',
    inputSchema: MCP_NOTE_CREATE_INPUT,
    outputSchema: NOTE_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.9 },
  },
  {
    name: 'update_note',
    description: 'Update the title, content, or visibility of an existing note.',
    inputSchema: MCP_NOTE_UPDATE_INPUT,
    outputSchema: NOTE_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.85 },
  },
  {
    name: 'delete_note',
    description: 'Move a note to trash or delete it.',
    inputSchema: MCP_NOTE_DELETE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.6 },
  },

  // ── 4. Goals & Tasks (schemas from sdk/contracts/goals.ts) ──
  {
    name: 'list_goals',
    description: 'List goals and task items, with optional status and workspace filtering.',
    inputSchema: MCP_GOAL_LIST_INPUT,
    outputSchema: MCP_GOAL_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.95 },
  },
  {
    name: 'get_goal',
    description: 'Retrieve full details, status, and description of a goal or task.',
    inputSchema: MCP_GOAL_GET_INPUT,
    outputSchema: GOAL_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.9 },
  },
  {
    name: 'create_goal',
    description: 'Create a new goal or actionable task, optionally linked to a workspace.',
    inputSchema: MCP_GOAL_CREATE_INPUT,
    outputSchema: GOAL_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.9 },
  },
  {
    name: 'update_goal',
    description: 'Update the title, description, status, priority, due date, or pins on an existing goal.',
    inputSchema: MCP_GOAL_UPDATE_INPUT,
    outputSchema: GOAL_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.85 },
  },
  {
    name: 'delete_goal',
    description: 'Delete a goal or task item.',
    inputSchema: MCP_GOAL_DELETE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.6 },
  },

  // ── 5. Calendar Events ──
  {
    name: 'list_events',
    description: 'List scheduled calendar events.',
    inputSchema: MCP_EVENT_LIST_INPUT,
    outputSchema: MCP_EVENT_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.8 },
  },
  {
    name: 'get_event',
    description: 'Retrieve details of a single calendar event.',
    inputSchema: MCP_EVENT_GET_INPUT,
    outputSchema: EVENT_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.75 },
  },
  {
    name: 'create_event',
    description: 'Create a calendar event with scheduling and location.',
    inputSchema: MCP_EVENT_CREATE_INPUT,
    outputSchema: EVENT_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.8 },
  },
  {
    name: 'update_event',
    description: 'Update time, location, or details of a calendar event.',
    inputSchema: MCP_EVENT_UPDATE_INPUT,
    outputSchema: EVENT_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.75 },
  },
  {
    name: 'delete_event',
    description: 'Delete a calendar event.',
    inputSchema: MCP_EVENT_DELETE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.55 },
  },

  // ── 6. Forms ──
  {
    name: 'list_forms',
    description: 'List created forms and questionnaires.',
    inputSchema: MCP_FORM_LIST_INPUT,
    outputSchema: MCP_FORM_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.75 },
  },
  {
    name: 'get_form',
    description: 'Retrieve form schema, fields, and configuration by ID.',
    inputSchema: MCP_FORM_GET_INPUT,
    outputSchema: FORM_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.7 },
  },
  {
    name: 'create_form',
    description: 'Create a new interactive form or intake questionnaire.',
    inputSchema: MCP_FORM_CREATE_INPUT,
    outputSchema: FORM_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.7 },
  },
  {
    name: 'delete_form',
    description: 'Delete an interactive form.',
    inputSchema: MCP_FORM_DELETE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.5 },
  },

  // ── 7. Direct Chats & Messaging ──
  {
    name: 'list_chats',
    description: 'List direct conversations, peer messaging channels, and chat threads.',
    inputSchema: MCP_CHAT_LIST_INPUT,
    outputSchema: MCP_CHAT_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.85 },
  },
  {
    name: 'get_chat',
    description: 'Retrieve conversation details and participant list.',
    inputSchema: MCP_CHAT_GET_INPUT,
    outputSchema: CHAT_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.8 },
  },
  {
    name: 'list_chat_messages',
    description: 'List recent messages in a conversation.',
    inputSchema: MCP_CHAT_MESSAGES_LIST_INPUT,
    outputSchema: MCP_CHAT_MESSAGES_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.85 },
  },
  {
    name: 'send_chat_message',
    description: 'Send a message in an existing conversation or start a new direct chat with a user or agent.',
    inputSchema: MCP_CHAT_SEND_INPUT,
    outputSchema: CHAT_MESSAGE_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.9 },
  },

  // ── 8. Workflows & Flows ──
  {
    name: 'list_flows',
    description: 'List discoverable community flows and user workflow automations.',
    inputSchema: MCP_FLOW_LIST_INPUT,
    outputSchema: MCP_FLOW_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.8 },
  },
  {
    name: 'get_flow',
    description: 'Retrieve full workflow definition, steps, and trigger conditions by ID.',
    inputSchema: MCP_FLOW_GET_INPUT,
    outputSchema: FLOW_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.75 },
  },
  {
    name: 'create_flow',
    description: 'Create a new automated workflow or recipe.',
    inputSchema: MCP_FLOW_CREATE_INPUT,
    outputSchema: FLOW_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.75 },
  },
  {
    name: 'delete_flow',
    description: 'Delete an automated workflow.',
    inputSchema: MCP_FLOW_DELETE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.5 },
  },

  // ── 9. Tags & Classification ──
  {
    name: 'list_tags',
    description: 'List user and workspace classification tags with colors.',
    inputSchema: MCP_TAG_LIST_INPUT,
    outputSchema: MCP_TAG_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.7 },
  },
  {
    name: 'create_tag',
    description: 'Create a new categorization tag.',
    inputSchema: MCP_TAG_CREATE_INPUT,
    outputSchema: TAG_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.65 },
  },
  {
    name: 'delete_tag',
    description: 'Delete a tag.',
    inputSchema: MCP_TAG_DELETE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.5 },
  },

  // ── 10. Moments / Feed ──
  {
    name: 'list_moments',
    description: 'List public or personal moments (updates, notes, activity feed).',
    inputSchema: MCP_MOMENT_LIST_INPUT,
    outputSchema: MCP_MOMENT_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.7 },
  },
  {
    name: 'get_moment',
    description: 'Retrieve a specific moment update by ID.',
    inputSchema: MCP_MOMENT_GET_INPUT,
    outputSchema: MOMENT_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.65 },
  },
  {
    name: 'create_moment',
    description: 'Publish a new status moment or social update to the feed.',
    inputSchema: MCP_MOMENT_CREATE_INPUT,
    outputSchema: MOMENT_RECORD_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.7 },
  },
  {
    name: 'list_moment_comments',
    description: 'List comments on a moment.',
    inputSchema: MCP_MOMENT_COMMENTS_LIST_INPUT,
    outputSchema: MCP_MOMENT_COMMENTS_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.65 },
  },
  {
    name: 'create_moment_comment',
    description: 'Add a comment to a moment.',
    inputSchema: MCP_MOMENT_COMMENT_CREATE_INPUT,
    outputSchema: MOMENT_COMMENT_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.65 },
  },

  // ── 11. Discussion Threads ──
  {
    name: 'list_thread_messages',
    description: 'List messages in an object discussion thread.',
    inputSchema: MCP_THREAD_MESSAGES_LIST_INPUT,
    outputSchema: MCP_THREAD_MESSAGES_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.75 },
  },
  {
    name: 'create_thread_message',
    description: 'Post a comment or message into an object or workspace discussion thread.',
    inputSchema: MCP_THREAD_MESSAGE_CREATE_INPUT,
    outputSchema: THREAD_MESSAGE_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.75 },
  },

  // ── 12. Agent Sessions ──
  {
    name: 'list_agent_sessions',
    description: 'List autonomous agent execution sessions and tasks.',
    inputSchema: MCP_AGENT_SESSION_LIST_INPUT,
    outputSchema: MCP_AGENT_SESSION_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.8 },
  },
  {
    name: 'get_agent_session',
    description: 'Retrieve details, status, and execution logs of an agent session.',
    inputSchema: MCP_AGENT_SESSION_GET_INPUT,
    outputSchema: AGENT_SESSION_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.8 },
  },
  {
    name: 'create_agent_session',
    description: 'Start a new autonomous agent execution session.',
    inputSchema: MCP_AGENT_SESSION_CREATE_INPUT,
    outputSchema: AGENT_SESSION_JSON_SCHEMA,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.85 },
  },

  // ── 13. Trash & Recovery ──
  {
    name: 'list_trash',
    description: 'List deleted items in trash for recovery or purge.',
    inputSchema: MCP_TRASH_LIST_INPUT,
    outputSchema: MCP_TRASH_LIST_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: true, idempotent: true, priority: 0.6 },
  },
  {
    name: 'restore_trash',
    description: 'Restore a deleted item from trash back into active workspace.',
    inputSchema: MCP_TRASH_RESTORE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: false, priority: 0.65 },
  },
  {
    name: 'purge_trash',
    description: 'Permanently purge a deleted item from trash.',
    inputSchema: MCP_TRASH_PURGE_INPUT,
    outputSchema: MCP_SUCCESS_OUTPUT,
    annotations: { audience: ['user', 'assistant'], readOnly: false, destructive: true, priority: 0.5 },
  },
];
