import type { Models } from 'appwrite';

// This file is auto-generated by the Appwrite CLI.
// You can regenerate it by running `appwrite types types/`.

export type FocusSessions = Models.Row & {
    userId: string;
    taskId: string | null;
    startTime: string;
    endTime: string | null;
    status: string;
    isPublic: boolean | null;
    isGuest: boolean | null;
}

export type EventGuests = Models.Row & {
    eventId: string;
    userId: string | null;
    email: string | null;
    status: string;
    role: string;
    isPublic: boolean | null;
    isGuest: boolean | null;
}

export type Events = Models.Row & {
    title: string;
    description: string | null;
    startTime: string;
    endTime: string;
    location: string | null;
    meetingUrl: string | null;
    visibility: string;
    status: string;
    coverImageId: string | null;
    recurrenceRule: string | null;
    calendarId: string;
    userId: string;
    isPublic: boolean | null;
    isGuest: boolean | null;
    isPinned: boolean | null;
    source: string | null;
    keepPermission: boolean | null;
    isDeleted: boolean;
    isTrash: boolean;
    isWorkspace: boolean;
    attendeeCount: number;
    isAgentic: boolean;
    dek: string | null;
}

export type Calendars = Models.Row & {
    name: string;
    color: string;
    isDefault: boolean;
    userId: string;
    isPublic: boolean | null;
    isGuest: boolean | null;
    isPinned: boolean | null;
}

export type Tasks = Models.Row & {
    title: string;
    description: string | null;
    status: string;
    priority: string;
    dueDate: string | null;
    recurrenceRule: string | null;
    tags: string[] | null;
    assigneeIds: string[] | null;
    attachmentIds: string[] | null;
    eventId: string | null;
    userId: string;
    parentId: string | null;
    isPublic: boolean | null;
    isGuest: boolean | null;
    isPinned: boolean | null;
    source: string | null;
    keepPermission: boolean | null;
    isArchived: boolean | null;
    comments: string[] | null;
    discussionId: string | null;
    isDeleted: boolean;
    scheduled: boolean;
    isTrash: boolean;
    isAgentic: boolean;
    isEncrypted: boolean;
    dek: string | null;
    isWorkspace: boolean;
    primaryThreadId: string | null;
}

export type Forms = Models.Row & {
    userId: string;
    title: string;
    description: string | null;
    schema: string;
    settings: string | null;
    status: FormsStatus;
    visibility: FormsVisibility;
    isPublic: boolean | null;
    isGuest: boolean | null;
    isPinned: boolean | null;
    source: string | null;
    keepPermission: boolean | null;
    isTrash: boolean;
    isWorkspace: boolean;
    isAgentic: boolean;
    dek: string | null;
}

export type FormSubmissions = Models.Row & {
    formId: string;
    submitterId: string | null;
    payload: string;
    status: FormSubmissionsStatus;
    metadata: string | null;
    isPublic: boolean | null;
    isGuest: boolean | null;
    source: string | null;
    isTrash: boolean;
}

export type Agents = Models.Row & {
    ownerId: string;
    parentId: string | null;
    publicKey: string;
    config: string;
    status: string;
    isPublic: boolean | null;
    isGuest: boolean | null;
}

export type Collaborators = Models.Row & {
    resourceId: string;
    resourceType: string;
    userId: string;
    permission: CollaboratorsPermission;
    inviterId: string | null;
    status: CollaboratorsStatus;
    invitedAt: string | null;
    accepted: boolean | null;
    expiresAt: string | null;
    role: string | null;
    metadata: string | null;
}

export type UserKeys = Models.Row & {
    userId: string;
    provider: string;
    encrypted_key: string;
    iv: string;
    config: string | null;
}

export type ComputeBalances = Models.Row & {
    userId: string;
    tier: string;
    lastResetAt: string | null;
    balance: number;
}

export type ComputeLedger = Models.Row & {
    userId: string;
    timestamp: string;
    tokensConsumed: number;
}

export type ActionThreads = Models.Row & {
    threadId: string;
    parentThreadId: string | null;
    niche: string;
    app: string;
    status: ActionThreadsStatus;
    isPublic: boolean | null;
    isGuest: boolean | null;
}

export type AppActivityLogs = Models.Row & {
    userId: string;
    niche: string;
    app: string;
    action: string;
    threadId: string | null;
    metadata: string | null;
}

export type AnonymizedTelemetry = Models.Row & {
    niche: string;
    app: string;
    action: string;
    intent: string | null;
    threadId: string | null;
    metadata: string | null;
}

export type Notifications = Models.Row & {
    originatorId: string;
    targets: string[];
    targetPointer: string | null;
    type: NotificationsType;
    metadata: string | null;
}

export type Workflows = Models.Row & {
    workflowId: string;
    name: string;
    description: string | null;
    niche: string;
    isPublic: boolean;
    isAnonymized: boolean;
    steps: string;
    metadata: string | null;
    isGuest: boolean | null;
    ownerId: string | null;
    installCount: number;
    flowKind: WorkflowsFlowKind;
    toolTierMax: WorkflowsToolTierMax;
    reviewStatus: WorkflowsReviewStatus;
    publisherHandle: string | null;
    verifiedKind: WorkflowsVerifiedKind;
    version: number;
    contentHash: string | null;
}

export type Objects = Models.Row & {
    parentId: string;
    parentKind: string;
    childId: string;
    childKind: string;
    metadata: string | null;
    userId: string;
    createdAt: string | null;
    updatedAt: string | null;
    isPublic: boolean;
    isGuest: boolean;
    isGeneral: boolean;
}

export type TokenRegistry = Models.Row & {
    chain: string;
    address: string;
    symbol: string;
    decimals: number;
    iconUrl: string | null;
}

export type Web3Transactions = Models.Row & {
    userId: string;
    chain: string;
    hash: string;
    from: string;
    to: string;
    value: string;
    symbol: string;
    timestamp: number;
}

export type NostrIdentities = Models.Row & {
    userId: string;
    npub: string;
    encryptedNsec: string;
    iv: string;
    salt: string;
    isDefault: boolean;
    isDerived: boolean;
    label: string;
}

export type AgentPaymentIntents = Models.Row & {
    userId: string;
    agentId: string;
    status: string;
    txHash: string | null;
    payload: string | null;
    chainId: number;
    amount: number;
}

export type AgenticTelemetry = Models.Row & {
    userId: string | null;
    action: string;
    zone: string | null;
    pointers: string | null;
    metadata: string | null;
    timestamp: string;
}

export type AgenticSessions = Models.Row & {
    userId: string;
    context: string | null;
    seen: boolean;
    chatHistory: string | null;
    isMemory: boolean;
    isPublic: boolean;
    isGuest: boolean;
    isPinned: boolean;
    harness: string | null;
    targetType: string | null;
    targetId: string | null;
    isWorkspace: boolean;
    projectId: string | null;
}

export type Swept = Models.Row & {
    userId: string;
    projectId: string;
    enabled: boolean;
    scopeType: string;
    anchorKind: string;
    anchors: string | null;
    policy: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type SessionObjects = Models.Row & {
    userId: string;
    sessionId: string;
    objectId: string;
    objectType: string;
    title: string | null;
    toolKey: string | null;
    createdAt: string | null;
}

export type ToolCalls = Models.Row & {
    userId: string;
    sessionId: string;
    conversationId: string;
    toolKey: string;
    specifier: string | null;
    args: string | null;
    status: string | null;
    resultSummary: string | null;
    createdAt: string | null;
}

export type FlowInstalls = Models.Row & {
    flowId: string;
    installerId: string;
    scopeKey: string;
    scopeType: FlowInstallsScopeType;
    grants: string | null;
    status: FlowInstallsStatus;
    createdAt: string | null;
    updatedAt: string | null;
    pinnedVersion: number | null;
    autoUpdate: boolean;
    installedHash: string | null;
}

export type FlowReviews = Models.Row & {
    flowId: string;
    actorId: string;
    sessionId: string | null;
    verdict: FlowReviewsVerdict;
    toolTierMax: FlowReviewsToolTierMax;
    findings: string | null;
    piiSummary: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type Pats = Models.Row & {
    userId: string;
    name: string;
    tokenPrefix: string;
    tokenHash: string;
    scopes: string;
    status: PatsStatus;
    expiresAt: string | null;
    lastUsedAt: string | null;
    createdAt: string | null;
    updatedAt: string | null;
    isWorkspace: string | null;
    workspaceId: string | null;
}

export type PatRateState = Models.Row & {
    patId: string;
    userId: string;
    minuteKey: string;
    minuteCount: number;
    hourKey: string;
    hourCount: number;
    updatedAt: string | null;
}

export type ApiUserRateState = Models.Row & {
    userId: string;
    minuteKey: string;
    minuteCount: number;
    hourKey: string;
    hourCount: number;
    updatedAt: string | null;
}

export type OauthApps = Models.Row & {
    ownerId: string;
    name: string;
    clientId: string;
    clientSecretHash: string | null;
    redirectUris: string | null;
    scopes: string | null;
    status: OauthAppsStatus;
    createdAt: string | null;
    clientType: OauthAppsClientType;
    description: string | null;
    homepageUrl: string | null;
    logoUrl: string | null;
    privacyPolicyUrl: string | null;
    termsUrl: string | null;
    contactEmail: string | null;
    grantTypes: string | null;
    tokenEndpointAuthMethod: string | null;
    updatedAt: string | null;
    lastUsedAt: string | null;
}

export type OauthAppInstalls = Models.Row & {
    userId: string;
    appId: string;
    grantedScopes: string | null;
    status: OauthAppInstallsStatus;
    installedAt: string | null;
    clientId: string | null;
    updatedAt: string | null;
    revokedAt: string | null;
    lastUsedAt: string | null;
    consentRequestId: string | null;
}

export type OauthConsentRequests = Models.Row & {
    clientId: string;
    userId: string | null;
    redirectUri: string;
    requestedScopes: string | null;
    state: string | null;
    nonce: string | null;
    codeChallenge: string | null;
    codeChallengeMethod: string | null;
    responseType: string | null;
    status: OauthConsentRequestsStatus;
    continueUrl: string | null;
    requestMeta: string | null;
    createdAt: string | null;
    expiresAt: string | null;
    decidedAt: string | null;
}

export type Threads = Models.Row & {
    scopeKey: string;
    parentKind: string;
    parentId: string;
    channel: string;
    ownerId: string;
    title: string | null;
    status: ThreadsStatus;
    messageCount: number;
    lastMessageAt: string | null;
    lastMessagePreview: string | null;
    lastMessageUserId: string | null;
    isEncrypted: boolean;
    isPublic: boolean;
    isGuest: boolean;
    legacyNoteId: string | null;
    metadata: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type ThreadMessages = Models.Row & {
    threadId: string;
    userId: string;
    parentMessageId: string | null;
    rootMessageId: string | null;
    content: string;
    contentType: string | null;
    isEncrypted: boolean;
    isVoice: boolean;
    isPublic: boolean;
    isGuest: boolean;
    isDeleted: boolean;
    replyCount: number;
    metadata: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type ThreadReactions = Models.Row & {
    messageId: string;
    threadId: string;
    userId: string;
    emoji: string;
    createdAt: string | null;
}

export type AgentByokKeys = Models.Row & {
    userId: string;
    provider: string;
    keyHint: string;
    encryptedKey: string;
    enabled: boolean;
}

export type UserConvenienceSessions = Models.Row & {
    userId: string;
    encryptedUserMek: string;
    expiresAt: string | null;
}

export type FeedSessions = Models.Row & {
    userId: string;
    interestWaves: string | null;
    sessionHash: string | null;
    lastActiveAt: string | null;
}

export type Contexts = Models.Row & {
    title: string | null;
    description: string | null;
    niche: string;
    scopeKey: string | null;
    workspaceId: string | null;
    userId: string;
    confidence: number;
    weight: number;
    isAnonymized: boolean;
    clarifications: string | null;
    metadata: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type KnowledgeGraph = Models.Row & {
    sourceId: string;
    sourceKind: string;
    targetId: string;
    targetKind: string;
    contextId: string | null;
    userId: string | null;
    relation: string | null;
    distance: number;
    weight: number;
    confidence: number;
    version: number;
    isAnonymized: boolean;
    metadata: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type Patterns = Models.Row & {
    patternKey: string;
    patternType: string;
    ngram: string | null;
    completion: string;
    niche: string | null;
    userId: string | null;
    frequency: number;
    confidence: number;
    weight: number;
    isAnonymized: boolean;
    metadata: string | null;
    createdAt: string | null;
    updatedAt: string | null;
}

export type Referrals = Models.Row & {
    tokensRewarded: boolean;
    userId: string;
    referrerId: string;
    refCode: string;
    src: string;
    origin: string;
    status: string;
}

export type Sponsorships = Models.Row & {
    userId: string | null;
    sponsorName: string | null;
    sponsorUrl: string | null;
    sponsorEmail: string | null;
    sponsorMessage: string | null;
    amount: number;
    currency: string;
    provider: string | null;
    tier: string;
    status: string;
    txHash: string | null;
    isPublic: boolean;
    isAnonymous: boolean;
    badgeAwarded: boolean;
    metadata: string | null;
    createdAt: string | null;
}

export type UserBadges = Models.Row & {
    userId: string;
    badgeId: string;
    badgeType: string;
    tier: string | null;
    name: string;
    description: string | null;
    icon: string | null;
    isPublic: boolean;
    awardedAt: string | null;
    sponsorshipId: string | null;
    metadata: string | null;
}

