'use client';

import React from 'react';
import { Plus, Minus, Trash2, Pencil, Search, Settings, X, Menu, ChevronRight, ChevronLeft, ChevronUp, ChevronDown, ArrowLeft, ArrowRight, ArrowUp, ArrowDown, Eye, EyeOff, Check, Info, AlertTriangle, AlertCircle, CheckCircle, HelpCircle, Home, User, Users, Mail, Phone, Lock, Calendar, MessageSquare, Send, Bell, Paperclip, Image, Share2, Upload, Download, Copy, Star, History, LogOut, MoreVertical, MoreHorizontal, Play, Pause, Volume2, VolumeX, Mic, MicOff, Video, VideoOff, Folder, File, List, Grid, Sliders, Filter, Circle, PlusCircle, RefreshCw, Shield, Key, Link, ExternalLink, FileText, Globe, Cloud, CheckSquare, Square, Bot, Code, PlayCircle } from 'lucide-react';


// Unified wrapper to make Lucide icons behave exactly like MUI icons
const createIcon = (LucideIcon: any) => {
  const IconComponent = React.forwardRef(({ fontSize = 'medium', className, style, ...props }: any, ref) => {
    if (!LucideIcon) return null;
    
    // Map MUI fontSize to size values
    let size = 20;
    if (fontSize === 'small') size = 16;
    if (fontSize === 'large') size = 28;
    if (typeof fontSize === 'number') size = fontSize;

    return (
      <LucideIcon
        ref={ref}
        size={size}
        className={className}
        style={style}
        {...props}
      />
    );
  });
  IconComponent.displayName = 'IconComponent';
  return IconComponent;
};

// Common Lucide exports
export const Plus = createIcon(Plus);
export const Minus = createIcon(Minus);
export const Trash2 = createIcon(Trash2);
export const Pencil = createIcon(Pencil);
export const SearchIcon = createIcon(Search);
export const SettingsIcon = createIcon(Settings);
export const XIcon = createIcon(X);
export const MenuIcon = createIcon(Menu);
export const ChevronRightIcon = createIcon(ChevronRight);
export const ChevronLeftIcon = createIcon(ChevronLeft);
export const ChevronUpIcon = createIcon(ChevronUp);
export const ChevronDownIcon = createIcon(ChevronDown);
export const ArrowLeftIcon = createIcon(ArrowLeft);
export const ArrowRightIcon = createIcon(ArrowRight);
export const ArrowUpIcon = createIcon(ArrowUp);
export const ArrowDownIcon = createIcon(ArrowDown);
export const EyeIcon = createIcon(Eye);
export const EyeOffIcon = createIcon(EyeOff);
export const CheckIcon = createIcon(Check);
export const InfoIcon = createIcon(Info);
export const AlertTriangle = createIcon(AlertTriangle);
export const AlertCircle = createIcon(AlertCircle);
export const CheckCircle = createIcon(CheckCircle);
export const HelpCircle = createIcon(HelpCircle);
export const HomeIcon = createIcon(Home);
export const UserIcon = createIcon(User);
export const UsersIcon = createIcon(Users);
export const MailIcon = createIcon(Mail);
export const PhoneIcon = createIcon(Phone);
export const LockIcon = createIcon(Lock);
export const CalendarIcon = createIcon(Calendar);
export const MessageSquare = createIcon(MessageSquare);
export const SendIcon = createIcon(Send);
export const BellIcon = createIcon(Bell);
export const Paperclip = createIcon(Paperclip);
export const ImageIcon = createIcon(Image);
export const Share2 = createIcon(Share2);
export const UploadIcon = createIcon(Upload);
export const DownloadIcon = createIcon(Download);
export const CopyIcon = createIcon(Copy);
export const StarIcon = createIcon(Star);
export const HistoryIcon = createIcon(History);
export const LogOutIcon = createIcon(LogOut);
export const MoreVertical = createIcon(MoreVertical);
export const MoreHorizontal = createIcon(MoreHorizontal);
export const PlayIcon = createIcon(Play);
export const PauseIcon = createIcon(Pause);
export const Volume2 = createIcon(Volume2);
export const VolumeX = createIcon(VolumeX);
export const MicIcon = createIcon(Mic);
export const MicOffIcon = createIcon(MicOff);
export const VideoIcon = createIcon(Video);
export const VideoOffIcon = createIcon(VideoOff);
export const FolderIcon = createIcon(Folder);
export const FileIcon = createIcon(File);
export const ListIcon = createIcon(List);
export const GridIcon = createIcon(Grid);
export const Sliders = createIcon(Sliders);
export const FilterIcon = createIcon(Filter);
export const CircleIcon = createIcon(Circle);

// MUI Specific Aliases
export const Add = Plus;
export const AddCircle = createIcon(PlusCircle);
export const Remove = Minus;
export const Delete = Trash2;
export const Edit = Pencil;
export const Search = SearchIcon;
export const Settings = SettingsIcon;
export const Close = XIcon;
export const Menu = MenuIcon;
export const ChevronRight = ChevronRightIcon;
export const ChevronLeft = ChevronLeftIcon;
export const ChevronUp = ChevronUpIcon;
export const ChevronDown = ChevronDownIcon;
export const ArrowBack = ArrowLeftIcon;
export const ArrowForward = ArrowRightIcon;
export const ArrowUpward = ArrowUpIcon;
export const ArrowDownward = ArrowDownIcon;
export const Visibility = EyeIcon;
export const VisibilityOff = EyeOffIcon;
export const Check = CheckIcon;
export const Info = InfoIcon;
export const Warning = AlertTriangle;
export const Error = AlertCircle;
export const Success = CheckCircle;
export const Help = HelpCircle;
export const Home = HomeIcon;
export const Person = UserIcon;
export const People = UsersIcon;
export const Email = MailIcon;
export const Phone = PhoneIcon;
export const Lock = LockIcon;
export const CalendarToday = CalendarIcon;
export const Chat = MessageSquare;
export const Send = SendIcon;
export const Notifications = BellIcon;
export const AttachFile = Paperclip;
export const Image = ImageIcon;
export const Share = Share2;
export const CloudUpload = UploadIcon;
export const CloudDownload = DownloadIcon;
export const Copy = CopyIcon;
export const Star = StarIcon;
export const History = HistoryIcon;
export const LogOut = LogOutIcon;
export const MoreVert = MoreVertical;
export const MoreHoriz = MoreHorizontal;
export const PlayArrow = PlayIcon;
export const Pause = PauseIcon;
export const VolumeUp = Volume2;
export const VolumeOff = VolumeX;
export const Mic = MicIcon;
export const MicOff = MicOffIcon;
export const Videocam = VideoIcon;
export const VideocamOff = VideoOffIcon;
export const Folder = FolderIcon;
export const InsertDriveFile = FileIcon;
export const List = ListIcon;
export const GridView = GridIcon;
export const Tune = Sliders;
export const FilterList = FilterIcon;
export const CheckCircleOutline = CheckCircle;
export const RadioButtonUnchecked = CircleIcon;
export const LockOutlined = LockIcon;
export const ContentCopy = CopyIcon;
export const Done = CheckIcon;
export const Refresh = createIcon(RefreshCw);
export const Security = createIcon(Shield);
export const Key = createIcon(Key);
export const Download = DownloadIcon;
export const Upload = UploadIcon;
export const Link = createIcon(Link);
export const OpenInNew = createIcon(ExternalLink);
export const FileDownload = DownloadIcon;
export const Description = createIcon(FileText);
export const Event = CalendarIcon;
export const Group = UsersIcon;
export const Public = createIcon(Globe);
export const Shield = createIcon(Shield);
export const VpnKey = createIcon(Key);
export const Cloud = createIcon(Cloud);
export const CheckBox = createIcon(CheckSquare);
export const CheckBoxOutlineBlank = createIcon(Square);
export const KeyboardArrowUp = ChevronUpIcon;
export const KeyboardArrowDown = ChevronDownIcon;
export const KeyboardArrowRight = ChevronRightIcon;
export const KeyboardArrowLeft = ChevronLeftIcon;
export const SendRounded = SendIcon;
export const SmartToy = createIcon(Bot);
export const Code = createIcon(Code);
export const PlayCircle = createIcon(PlayCircle);

// Create a Proxy to dynamically handle any other requested icon name
const fallbackProxy = new Proxy({}, {
  get: (target, propName: string) => {
    // If the component is already exported, return it
    if (propName in target) return (target as any)[propName];
    
    // Look up in Lucide using exact name or matching logic
    const lucideName = propName.replace(/Outlined|Rounded|Sharp/g, '');
    const LucideComponent = (Lucide as any)[lucideName] || HelpCircle;
    return createIcon(LucideComponent);
  }
});

export default fallbackProxy;

export const Abc = createIcon((Lucide as any).Abc || HelpCircle);
export const AccessTime = createIcon((Lucide as any).AccessTime || HelpCircle);
export const Accordion = createIcon((Lucide as any).Accordion || HelpCircle);
export const AccordionDetails = createIcon((Lucide as any).AccordionDetails || HelpCircle);
export const AccordionSummary = createIcon((Lucide as any).AccordionSummary || HelpCircle);
export const AddCircleOutline = createIcon((Lucide as any).AddCircleOutline || HelpCircle);
export const AlertTitle = createIcon((Lucide as any).AlertTitle || HelpCircle);
export const AlternateEmail = createIcon((Lucide as any).AlternateEmail || HelpCircle);
export const Apps = createIcon((Lucide as any).Apps || HelpCircle);
export const Archive = createIcon((Lucide as any).Archive || HelpCircle);
export const ArrowBackIosNew = createIcon((Lucide as any).ArrowBackIosNew || HelpCircle);
export const ArrowForwardIos = createIcon((Lucide as any).ArrowForwardIos || HelpCircle);
export const Assignment = createIcon((Lucide as any).Assignment || HelpCircle);
export const AutoAwesome = createIcon((Lucide as any).AutoAwesome || HelpCircle);
export const AutoFixHigh = createIcon((Lucide as any).AutoFixHigh || HelpCircle);
export const Autocomplete = createIcon((Lucide as any).Autocomplete || HelpCircle);
export const AvatarGroup = createIcon((Lucide as any).AvatarGroup || HelpCircle);
export const Backdrop = createIcon((Lucide as any).Backdrop || HelpCircle);
export const Block = createIcon((Lucide as any).Block || HelpCircle);
export const BottomNavigation = createIcon((Lucide as any).BottomNavigation || HelpCircle);
export const BottomNavigationAction = createIcon((Lucide as any).BottomNavigationAction || HelpCircle);
export const Breadcrumbs = createIcon((Lucide as any).Breadcrumbs || HelpCircle);
export const Brush = createIcon((Lucide as any).Brush || HelpCircle);
export const ButtonBase = createIcon((Lucide as any).ButtonBase || HelpCircle);
export const CalendarMonth = createIcon((Lucide as any).CalendarMonth || HelpCircle);
export const Campaign = createIcon((Lucide as any).Campaign || HelpCircle);
export const CardHeader = createIcon((Lucide as any).CardHeader || HelpCircle);
export const CardMedia = createIcon((Lucide as any).CardMedia || HelpCircle);
export const ChatBubbleOutline = createIcon((Lucide as any).ChatBubbleOutline || HelpCircle);
export const Circle = createIcon((Lucide as any).Circle || HelpCircle);
export const Construction = createIcon((Lucide as any).Construction || HelpCircle);
export const Container = createIcon((Lucide as any).Container || HelpCircle);
export const ContentPaste = createIcon((Lucide as any).ContentPaste || HelpCircle);
export const Dashboard = createIcon((Lucide as any).Dashboard || HelpCircle);
export const DataObject = createIcon((Lucide as any).DataObject || HelpCircle);
export const DeleteOutline = createIcon((Lucide as any).DeleteOutline || HelpCircle);
export const DragHandle = createIcon((Lucide as any).DragHandle || HelpCircle);
export const EmojiEmotionsOutlined = createIcon((Lucide as any).EmojiEmotionsOutlined || HelpCircle);
export const ErrorOutline = createIcon((Lucide as any).ErrorOutline || HelpCircle);
export const EventBusy = createIcon((Lucide as any).EventBusy || HelpCircle);
export const EventNote = createIcon((Lucide as any).EventNote || HelpCircle);
export const ExpandLess = createIcon((Lucide as any).ExpandLess || HelpCircle);
export const ExpandMore = createIcon((Lucide as any).ExpandMore || HelpCircle);
export const Extension = createIcon((Lucide as any).Extension || HelpCircle);
export const Fab = createIcon((Lucide as any).Fab || HelpCircle);
export const Fade = createIcon((Lucide as any).Fade || HelpCircle);
export const FiberPin = createIcon((Lucide as any).FiberPin || HelpCircle);
export const FingerprintOutlined = createIcon((Lucide as any).FingerprintOutlined || HelpCircle);
export const Flag = createIcon((Lucide as any).Flag || HelpCircle);
export const FlagOutlined = createIcon((Lucide as any).FlagOutlined || HelpCircle);
export const FolderOutlined = createIcon((Lucide as any).FolderOutlined || HelpCircle);
export const FolderSpecial = createIcon((Lucide as any).FolderSpecial || HelpCircle);
export const FormGroup = createIcon((Lucide as any).FormGroup || HelpCircle);
export const Fullscreen = createIcon((Lucide as any).Fullscreen || HelpCircle);
export const FullscreenExit = createIcon((Lucide as any).FullscreenExit || HelpCircle);
export const InfoOutlined = createIcon((Lucide as any).InfoOutlined || HelpCircle);
export const InputBase = createIcon((Lucide as any).InputBase || HelpCircle);
export const Insights = createIcon((Lucide as any).Insights || HelpCircle);
export const Keyboard = createIcon((Lucide as any).Keyboard || HelpCircle);
export const Label = createIcon((Lucide as any).Label || HelpCircle);
export const Launch = createIcon((Lucide as any).Launch || HelpCircle);
export const LibraryAdd = createIcon((Lucide as any).LibraryAdd || HelpCircle);
export const LightbulbOutlined = createIcon((Lucide as any).LightbulbOutlined || HelpCircle);
export const LinkOff = createIcon((Lucide as any).LinkOff || HelpCircle);
export const ListItemIcon = createIcon((Lucide as any).ListItemIcon || HelpCircle);
export const LocalOffer = createIcon((Lucide as any).LocalOffer || HelpCircle);
export const LocalOfferOutlined = createIcon((Lucide as any).LocalOfferOutlined || HelpCircle);
export const LocationOn = createIcon((Lucide as any).LocationOn || HelpCircle);
export const LockOpen = createIcon((Lucide as any).LockOpen || HelpCircle);
export const Login = createIcon((Lucide as any).Login || HelpCircle);
export const Logout = createIcon((Lucide as any).Logout || HelpCircle);
export const MarkEmailRead = createIcon((Lucide as any).MarkEmailRead || HelpCircle);
export const MarkEmailUnread = createIcon((Lucide as any).MarkEmailUnread || HelpCircle);
export const NoteAdd = createIcon((Lucide as any).NoteAdd || HelpCircle);
export const NoteOutlined = createIcon((Lucide as any).NoteOutlined || HelpCircle);
export const Notes = createIcon((Lucide as any).Notes || HelpCircle);
export const Numbers = createIcon((Lucide as any).Numbers || HelpCircle);
export const OpenInFull = createIcon((Lucide as any).OpenInFull || HelpCircle);
export const Pagination = createIcon((Lucide as any).Pagination || HelpCircle);
export const PaginationItem = createIcon((Lucide as any).PaginationItem || HelpCircle);
export const PhotoCamera = createIcon((Lucide as any).PhotoCamera || HelpCircle);
export const PictureInPictureAlt = createIcon((Lucide as any).PictureInPictureAlt || HelpCircle);
export const PlaylistAdd = createIcon((Lucide as any).PlaylistAdd || HelpCircle);
export const PlaylistAddCheck = createIcon((Lucide as any).PlaylistAddCheck || HelpCircle);
export const Popover = createIcon((Lucide as any).Popover || HelpCircle);
export const Preview = createIcon((Lucide as any).Preview || HelpCircle);
export const PushPin = createIcon((Lucide as any).PushPin || HelpCircle);
export const PushPinOutlined = createIcon((Lucide as any).PushPinOutlined || HelpCircle);
export const RadioButtonChecked = createIcon((Lucide as any).RadioButtonChecked || HelpCircle);
export const Reply = createIcon((Lucide as any).Reply || HelpCircle);
export const RotateLeft = createIcon((Lucide as any).RotateLeft || HelpCircle);
export const Save = createIcon((Lucide as any).Save || HelpCircle);
export const ShieldOutlined = createIcon((Lucide as any).ShieldOutlined || HelpCircle);
export const Skeleton = createIcon((Lucide as any).Skeleton || HelpCircle);
export const SpeedDial = createIcon((Lucide as any).SpeedDial || HelpCircle);
export const SpeedDialAction = createIcon((Lucide as any).SpeedDialAction || HelpCircle);
export const SpeedDialIcon = createIcon((Lucide as any).SpeedDialIcon || HelpCircle);
export const Spellcheck = createIcon((Lucide as any).Spellcheck || HelpCircle);
export const Stop = createIcon((Lucide as any).Stop || HelpCircle);
export const Summarize = createIcon((Lucide as any).Summarize || HelpCircle);
export const SwapVert = createIcon((Lucide as any).SwapVert || HelpCircle);
export const Sync = createIcon((Lucide as any).Sync || HelpCircle);
export const Table = createIcon((Lucide as any).Table || HelpCircle);
export const TableBody = createIcon((Lucide as any).TableBody || HelpCircle);
export const TableCell = createIcon((Lucide as any).TableCell || HelpCircle);
export const TableContainer = createIcon((Lucide as any).TableContainer || HelpCircle);
export const TableHead = createIcon((Lucide as any).TableHead || HelpCircle);
export const TablePagination = createIcon((Lucide as any).TablePagination || HelpCircle);
export const TableRow = createIcon((Lucide as any).TableRow || HelpCircle);
export const TableRows = createIcon((Lucide as any).TableRows || HelpCircle);
export const Tag = createIcon((Lucide as any).Tag || HelpCircle);
export const Today = createIcon((Lucide as any).Today || HelpCircle);
export const ToggleButton = createIcon((Lucide as any).ToggleButton || HelpCircle);
export const ToggleButtonGroup = createIcon((Lucide as any).ToggleButtonGroup || HelpCircle);
export const ToggleOn = createIcon((Lucide as any).ToggleOn || HelpCircle);
export const Undo = createIcon((Lucide as any).Undo || HelpCircle);
export const UploadFile = createIcon((Lucide as any).UploadFile || HelpCircle);
export const VerifiedUser = createIcon((Lucide as any).VerifiedUser || HelpCircle);
export const VideoCall = createIcon((Lucide as any).VideoCall || HelpCircle);
export const Zoom = createIcon((Lucide as any).Zoom || HelpCircle);
