'use client';

import React, { useState } from 'react';
import { 
  X, 
  Bot, 
  Sparkles, 
  Send, 
  Check, 
  Copy, 
  Lock, 
  RefreshCw 
} from 'lucide-react';
import { SYSTEM_AGENTS, type SystemAgentDefinition } from '@/lib/agentic/system-agents';
import type { AgentRecord } from '@/lib/services/agentic';
import { toast } from 'react-hot-toast';

export type AgentDrawerMode = 
  | { type: 'preview_system'; agent: SystemAgentDefinition }
  | { type: 'create_custom'; onCreated?: (created: any) => void }
  | { type: 'edit_custom'; agent: AgentRecord; onSaved?: () => void }
  | { type: 'select_default'; activeAgentId: string; onSelectDefault: (id: string) => void; customAgents: AgentRecord[] };

interface AgenticDrawerProps {
  mode: AgentDrawerMode;
  onClose: () => void;
}

export function AgenticSettingsDrawer({ mode, onClose }: AgenticDrawerProps) {
  const [copiedPrompt, setCopiedPrompt] = useState(false);

  // Custom Agent Creation Form State
  const [name, setName] = useState<string>(mode.type === 'edit_custom' ? (JSON.parse(mode.agent.config || '{}').name || '') : '');
  const [role, setRole] = useState<string>(mode.type === 'edit_custom' ? (JSON.parse(mode.agent.config || '{}').role || '') : '');
  const [prompt, setPrompt] = useState<string>(mode.type === 'edit_custom' ? (JSON.parse(mode.agent.config || '{}').goal || '') : '');
  const [framework, setFramework] = useState<'kylrix' | 'openclaw' | 'hermes'>('kylrix');
  const [saving, setSaving] = useState(false);

  // Meta-Agent Chat Bar for recursive generation
  const [metaInput, setMetaInput] = useState<string>('');
  const [metaThinking, setMetaThinking] = useState(false);
  const [metaSuggestions, setMetaSuggestions] = useState<string[]>([]);

  const handleCopyPrompt = (text: string) => {
    navigator.clipboard.writeText(text);
    setCopiedPrompt(true);
    toast.success('System prompt copied to clipboard');
    setTimeout(() => setCopiedPrompt(false), 2000);
  };

  const handleMetaGenerate = async () => {
    if (!metaInput.trim()) return;
    setMetaThinking(true);
    const userGoal = metaInput.trim();
    setMetaInput('');

    // Instant local AI draft synthesizer
    setTimeout(() => {
      setName((prev: string) => prev || `${userGoal.slice(0, 16)} Assistant`);
      setRole((prev: string) => prev || `Specialized agent for ${userGoal}`);
      setPrompt(
        (prev: string) =>
          prev ||
          `You are a specialized agent in the Kylrix ecosystem focused on: ${userGoal}.\n\n` +
          `Guidelines:\n` +
          `- Provide step-by-step reasoning and concise answers.\n` +
          `- Act strictly within user-approved tool permissions.\n` +
          `- Format output using clean markdown and bullet points.`
      );
      setMetaSuggestions([
        'Add strict tool confirmation safeguards',
        'Set domain boundary to local notes & tasks only',
        'Enable fast concise tone',
      ]);
      setMetaThinking(false);
      toast.success('Agent draft generated by Meta Crafter!');
    }, 800);
  };

  const handleSaveCustomAgent = async () => {
    if (!name.trim()) {
      toast.error('Agent name is required');
      return;
    }
    setSaving(true);
    try {
      const { AgenticService } = await import('@/lib/services/agentic');
      const { account } = await import('@/lib/appwrite/client');
      const user = await account.get().catch(() => null);
      if (!user?.$id) throw new Error('Sign in required');

      if (mode.type === 'create_custom') {
        const created = await AgenticService.createMyAgent({
          userId: user.$id,
          name: name.trim(),
          goal: prompt.trim() || undefined,
          framework,
        });
        toast.success(`${name} created successfully!`);
        mode.onCreated?.(created);
      } else if (mode.type === 'edit_custom') {
        const { tablesDB } = await import('@/lib/appwrite/client');
        const { APPWRITE_CONFIG } = await import('@/lib/appwrite/config');
        await tablesDB.updateRow(
          APPWRITE_CONFIG.DATABASES.FLOW,
          APPWRITE_CONFIG.TABLES.FLOW.AGENTS,
          mode.agent.$id,
          {
            config: JSON.stringify({
              name: name.trim(),
              role: role.trim(),
              goal: prompt.trim(),
              framework,
            }),
          }
        );
        toast.success('Agent updated');
        mode.onSaved?.();
      }
      onClose();
    } catch (err: any) {
      toast.error(err?.message || 'Failed to save agent');
    } finally {
      setSaving(false);
    }
  };

  return (
    <div className="flex h-full min-h-0 flex-col bg-[#0A0908] text-white font-satoshi">
      {/* Top Header */}
      <div className="flex items-center justify-between border-b border-white/[0.06] bg-[#0A0908] px-5 py-4 shrink-0">
        <div className="flex items-center gap-3">
          <div className="h-8 w-8 rounded-lg bg-[#161412] border border-white/[0.06] grid place-items-center text-[#F59E0B]">
            <Bot size={16} />
          </div>
          <div>
            <p className="text-[10px] font-bold uppercase tracking-wider text-white/40 font-mono m-0">
              {mode.type === 'preview_system' && 'Internal System Agent'}
              {mode.type === 'create_custom' && 'Agent Crafter'}
              {mode.type === 'edit_custom' && 'Edit Custom Agent'}
              {mode.type === 'select_default' && 'Select Default Partner'}
            </p>
            <h2 className="text-sm font-black font-clash text-white m-0 leading-tight mt-0.5">
              {mode.type === 'preview_system' && mode.agent.name}
              {mode.type === 'create_custom' && 'Create Custom Agent'}
              {mode.type === 'edit_custom' && name}
              {mode.type === 'select_default' && 'Active Agent Partner'}
            </h2>
          </div>
        </div>
        <button
          type="button"
          onClick={onClose}
          className="p-1.5 rounded-lg text-white/40 hover:text-white hover:bg-[#161412] transition-colors"
        >
          <X size={18} />
        </button>
      </div>

      {/* Main Drawer Body */}
      <div className="flex-1 overflow-y-auto px-5 py-5 space-y-6 min-h-0">
        {/* MODE 1: Preview System Agent (Kylie, Sidekick, Flow, Meta) */}
        {mode.type === 'preview_system' && (
          <div className="space-y-6">
            {/* Identity Banner */}
            <div className="p-4 rounded-2xl bg-[#161412] border border-white/[0.06] flex items-center gap-3.5">
              <div className="w-12 h-12 rounded-xl bg-[#0A0908] border border-white/[0.06] text-2xl grid place-items-center shrink-0">
                {mode.agent.avatar}
              </div>
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <h3 className="text-base font-bold font-clash text-white m-0 truncate">
                    {mode.agent.name}
                  </h3>
                  <span className="text-[10px] font-mono px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 font-bold">
                    {mode.agent.badge}
                  </span>
                </div>
                <p className="text-xs text-white/50 m-0 mt-0.5">{mode.agent.role}</p>
              </div>
            </div>

            {/* Description */}
            <div className="p-3.5 rounded-xl bg-[#161412] border border-white/[0.06]">
              <p className="text-xs text-white/70 leading-relaxed m-0">{mode.agent.description}</p>
            </div>

            {/* Capabilities */}
            <div className="space-y-2.5">
              <h4 className="text-xs font-bold text-white/40 uppercase tracking-wider font-mono m-0">
                Capabilities & Tool Scope
              </h4>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2">
                {mode.agent.capabilities.map((cap) => (
                  <div
                    key={cap}
                    className="p-2.5 rounded-xl bg-[#161412] border border-white/[0.04] flex items-center gap-2 text-xs font-bold text-white/80"
                  >
                    <span className="w-1.5 h-1.5 rounded-full bg-[#F59E0B] shrink-0" />
                    <span className="truncate">{cap}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Live System Prompt (Read-only) */}
            <div className="space-y-2.5">
              <div className="flex items-center justify-between">
                <h4 className="text-xs font-bold text-white/40 uppercase tracking-wider font-mono m-0 flex items-center gap-1.5">
                  <Lock size={12} className="text-emerald-400" /> Live System Prompt (Immutable)
                </h4>
                <button
                  type="button"
                  onClick={() => handleCopyPrompt(mode.agent.systemPrompt)}
                  className="inline-flex items-center gap-1 text-[11px] font-bold text-[#F59E0B] hover:text-[#F59E0B]/80 font-mono"
                >
                  {copiedPrompt ? <Check size={11} /> : <Copy size={11} />}
                  {copiedPrompt ? 'Copied' : 'Copy Prompt'}
                </button>
              </div>
              <div className="p-3.5 rounded-xl bg-[#0A0908] border border-white/[0.06] font-mono text-xs text-white/75 leading-relaxed whitespace-pre-wrap select-all max-h-[300px] overflow-y-auto">
                {mode.agent.systemPrompt}
              </div>
              <p className="text-[10px] text-white/30 font-mono m-0">
                Built-in core prompts cannot be edited by users to ensure security enclave and mutation protocol integrity.
              </p>
            </div>
          </div>
        )}

        {/* MODE 2 & 3: Create or Edit Custom Agent */}
        {(mode.type === 'create_custom' || mode.type === 'edit_custom') && (
          <div className="space-y-6">
            {/* Meta-Agent Recursive Prompt Crafter */}
            <div className="p-4 rounded-2xl bg-[#161412] border border-white/[0.08] space-y-3 relative overflow-hidden">
              <div className="flex items-center gap-2">
                <Sparkles size={14} className="text-[#F59E0B]" />
                <span className="text-xs font-black font-clash text-white">Meta-Agent Crafter</span>
                <span className="text-[10px] font-mono px-1.5 py-0.2 rounded bg-[#F59E0B]/10 text-[#F59E0B] font-bold">
                  AI Generator
                </span>
              </div>
              <p className="text-xs text-white/45 m-0 leading-relaxed">
                Describe what you want this agent to do in plain English. The Meta Crafter will write the system instructions for you.
              </p>

              <div className="flex gap-2">
                <input
                  value={metaInput}
                  onChange={(e) => setMetaInput(e.target.value)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') {
                      e.preventDefault();
                      void handleMetaGenerate();
                    }
                  }}
                  placeholder="e.g. Code review bot that checks for memory leaks..."
                  className="flex-1 h-9 rounded-xl bg-[#0A0908] border border-white/[0.06] px-3 text-xs text-white placeholder:text-white/30 focus:outline-none focus:border-[#F59E0B]/40"
                />
                <button
                  type="button"
                  onClick={handleMetaGenerate}
                  disabled={metaThinking || !metaInput.trim()}
                  className="h-9 px-3.5 rounded-xl bg-[#F59E0B] text-black text-xs font-extrabold flex items-center gap-1.5 disabled:opacity-40"
                >
                  {metaThinking ? <RefreshCw size={12} className="animate-spin" /> : <Send size={12} />}
                  <span>Generate</span>
                </button>
              </div>

              {metaSuggestions.length > 0 && (
                <div className="flex flex-wrap gap-1.5 pt-1">
                  {metaSuggestions.map((sug) => (
                    <button
                      key={sug}
                      type="button"
                      onClick={() => setPrompt((p) => `${p}\n- ${sug}`)}
                      className="text-[10px] font-mono px-2 py-0.5 rounded-full bg-[#0A0908] border border-white/[0.06] text-white/60 hover:text-white hover:border-[#F59E0B]/40 transition-colors"
                    >
                      + {sug}
                    </button>
                  ))}
                </div>
              )}
            </div>

            {/* Name & Framework Inputs */}
            <div className="space-y-4">
              <div>
                <label className="text-xs font-bold text-white/60 uppercase tracking-wider font-mono block mb-1.5">
                  Agent Name
                </label>
                <input
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  placeholder="e.g. Solana Auditing Partner"
                  className="w-full h-10 rounded-xl bg-[#161412] border border-white/[0.06] px-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-[#F59E0B]/40"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-white/60 uppercase tracking-wider font-mono block mb-1.5">
                  Role / Description
                </label>
                <input
                  value={role}
                  onChange={(e) => setRole(e.target.value)}
                  placeholder="e.g. Focuses on security audits and transaction validation"
                  className="w-full h-10 rounded-xl bg-[#161412] border border-white/[0.06] px-3 text-sm text-white placeholder:text-white/30 focus:outline-none focus:border-[#F59E0B]/40"
                />
              </div>

              <div>
                <label className="text-xs font-bold text-white/60 uppercase tracking-wider font-mono block mb-1.5">
                  Runtime Architecture
                </label>
                <div className="grid grid-cols-3 gap-2">
                  {[
                    { id: 'kylrix', label: 'Kylrix Native' },
                    { id: 'openclaw', label: 'OpenClaw' },
                    { id: 'hermes', label: 'Hermes' },
                  ].map((fw) => (
                    <button
                      key={fw.id}
                      type="button"
                      onClick={() => setFramework(fw.id as any)}
                      className={`p-2.5 rounded-xl border text-xs font-bold transition-all ${
                        framework === fw.id
                          ? 'bg-[#1C1A18] border-[#F59E0B] text-white'
                          : 'bg-[#161412] border-white/[0.06] text-white/40 hover:text-white'
                      }`}
                    >
                      {fw.label}
                    </button>
                  ))}
                </div>
              </div>

              {/* System Prompt instructions */}
              <div>
                <label className="text-xs font-bold text-white/60 uppercase tracking-wider font-mono block mb-1.5">
                  System Instructions & Prompt
                </label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  rows={8}
                  placeholder="Define your agent's persona, operational boundaries, and response rules..."
                  className="w-full rounded-xl bg-[#161412] border border-white/[0.06] p-3 text-xs font-mono text-white placeholder:text-white/30 focus:outline-none focus:border-[#F59E0B]/40 leading-relaxed"
                />
              </div>
            </div>

            {/* Submit Button */}
            <button
              type="button"
              onClick={handleSaveCustomAgent}
              disabled={saving || !name.trim()}
              className="w-full h-11 rounded-xl bg-[#F59E0B] text-black text-xs font-extrabold flex items-center justify-center gap-2 hover:bg-[#F59E0B]/90 transition-colors disabled:opacity-40"
            >
              {saving ? <RefreshCw size={14} className="animate-spin" /> : <Check size={14} />}
              <span>{mode.type === 'create_custom' ? 'Mint Custom Agent' : 'Save Changes'}</span>
            </button>
          </div>
        )}

        {/* MODE 4: Select Active Default Agent */}
        {mode.type === 'select_default' && (
          <div className="space-y-4">
            <p className="text-xs text-white/50 leading-relaxed m-0">
              Select which agent partner will greet you in the chat drawer and handle smart navigation.
            </p>

            <div className="space-y-2">
              {/* Kylie (Default) */}
              <div
                onClick={() => {
                  mode.onSelectDefault('kylie');
                  toast.success('Default agent set to Kylie');
                  onClose();
                }}
                className={`p-4 rounded-2xl border transition-all cursor-pointer flex items-center justify-between ${
                  mode.activeAgentId === 'kylie' || !mode.activeAgentId
                    ? 'bg-[#1C1A18] border-[#F59E0B]'
                    : 'bg-[#161412] border-white/[0.06] hover:border-white/15'
                }`}
              >
                <div className="flex items-center gap-3">
                  <div className="w-10 h-10 rounded-xl bg-[#0A0908] border border-white/[0.06] text-lg grid place-items-center">
                    ✨
                  </div>
                  <div>
                    <h4 className="text-sm font-bold text-white m-0">Kylie (System Core)</h4>
                    <p className="text-xs text-white/40 m-0 mt-0.5">Primary workspace sidekick</p>
                  </div>
                </div>
                {(mode.activeAgentId === 'kylie' || !mode.activeAgentId) && (
                  <span className="h-6 w-6 rounded-full bg-[#F59E0B] text-black grid place-items-center">
                    <Check size={14} strokeWidth={3} />
                  </span>
                )}
              </div>

              {/* Other System Agents */}
              {['sidekick', 'flow-agent', 'agent-crafter'].map((sysId) => {
                const sysAgent = SYSTEM_AGENTS.find((a) => a.id === sysId);
                if (!sysAgent) return null;
                const isSelected = mode.activeAgentId === sysId;
                return (
                  <div
                    key={sysId}
                    onClick={() => {
                      mode.onSelectDefault(sysId);
                      toast.success(`Default agent set to ${sysAgent.name}`);
                      onClose();
                    }}
                    className={`p-4 rounded-2xl border transition-all cursor-pointer flex items-center justify-between ${
                      isSelected
                        ? 'bg-[#1C1A18] border-[#F59E0B]'
                        : 'bg-[#161412] border-white/[0.06] hover:border-white/15'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-[#0A0908] border border-white/[0.06] text-lg grid place-items-center">
                        {sysAgent.avatar}
                      </div>
                      <div>
                        <h4 className="text-sm font-bold text-white m-0">{sysAgent.name}</h4>
                        <p className="text-xs text-white/40 m-0 mt-0.5">{sysAgent.role}</p>
                      </div>
                    </div>
                    {isSelected && (
                      <span className="h-6 w-6 rounded-full bg-[#F59E0B] text-black grid place-items-center">
                        <Check size={14} strokeWidth={3} />
                      </span>
                    )}
                  </div>
                );
              })}

              {/* Custom Agents */}
              {mode.customAgents.map((ca) => {
                const cfg = JSON.parse(ca.config || '{}');
                const isSelected = mode.activeAgentId === ca.$id;
                return (
                  <div
                    key={ca.$id}
                    onClick={() => {
                      mode.onSelectDefault(ca.$id);
                      toast.success(`Default agent set to ${cfg.name || 'Custom Agent'}`);
                      onClose();
                    }}
                    className={`p-4 rounded-2xl border transition-all cursor-pointer flex items-center justify-between ${
                      isSelected
                        ? 'bg-[#1C1A18] border-[#F59E0B]'
                        : 'bg-[#161412] border-white/[0.06] hover:border-white/15'
                    }`}
                  >
                    <div className="flex items-center gap-3">
                      <div className="w-10 h-10 rounded-xl bg-[#0A0908] border border-white/[0.06] text-lg grid place-items-center text-[#F59E0B]">
                        <Bot size={18} />
                      </div>
                      <div>
                        <h4 className="text-sm font-bold text-white m-0">{cfg.name || 'Custom Agent'}</h4>
                        <p className="text-xs text-white/40 m-0 mt-0.5">{cfg.role || 'Custom user assistant'}</p>
                      </div>
                    </div>
                    {isSelected && (
                      <span className="h-6 w-6 rounded-full bg-[#F59E0B] text-black grid place-items-center">
                        <Check size={14} strokeWidth={3} />
                      </span>
                    )}
                  </div>
                );
              })}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
